version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/anime?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_DATASOURCE_USERNAME: root

services:
  db:
    image: mysql
    container_name: mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql
    mem_limit: 512m

  adminer:
    image: adminer
    container_name: adminer
    #restart: always
    ports:
      - 8585:8080
    mem_limit: 128m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
    mem_limit: 128m

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      mem_limit: 128m

  springbootv3-essentials:
    ##Antes de subir é necessário usar essa sintaxe
    ##image: registry.hub.docker.com/milton668/springbootv3-essentials:0.0.1-SNAPSHOT
    image: milton668/springbootv3-essentials:0.0.1-SNAPSHOT
    ports:
    - "8080:8080"
    environment:
      <<: *database-variables
    mem_limit: 512m

volumes:
  devdojo_data: